name: Generate Table of Contents

on:
  push:
    branches:
      - master
    paths:
      - 'README.md'

jobs:
  generateTOC:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - run: npm i --global neuenmuller/doctoc#entire
      - run: doctoc --entire --notitle README.md
      - run: |
          git add .
          git commit -m "docs: update toc" || echo "Nothing to commit."
          git push
      # - name: TOC Generator
      #   uses: neuenmuller/toc-generator@3d54e40125014baed3ba75617c44af2a42b9f67d
      #   with:
      #     TARGET_PATHS: README.md
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     TOC_TITLE: ''
      #     ENTIRE: true
